name: Publish Package

on:
  push:
    branches:
      - trunk
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Checkout discord-api-spec
        uses: actions/checkout@v4
        with:
          repository: discord/discord-api-spec
          path: openapi

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Release
        run: pnpm release
